global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: risingwave
    static_configs:
      - targets: ["risingwave-standalone:1250"]
        labels:
          instance: risingwave
